[15.0][mig]-hr_payroll_period
OCA/payroll pull request #120
Opened 2023-03-01 16:35 UTC by JuanyDForgeflow

Migration to 15.0

2023-05-19 09:35 UTC, hieulucky111 commented on hr_payroll_period/models/hr_fiscal_year.py
> +        no_interval = 1
should add `self.ensure_one()`?

2023-05-19 10:03 UTC, hieulucky111 requested changes

2023-05-19 10:03 UTC, hieulucky111 commented on hr_payroll_period/models/hr_fiscal_year.py
> +            period_start = datetime.strptime(str(self.date_start), DF)
`strptime(str(self.date_start), DF)`

2023-05-19 10:03 UTC, hieulucky111 commented on hr_payroll_period/models/hr_fiscal_year.py
> +            next_year_start = datetime.strptime(str(self.date_end), DF) + relativedelta(
`strptime(str(self.date_end), DF) + relativedelta(days=1)`

2023-05-19 10:03 UTC, hieulucky111 commented on hr_payroll_period/models/hr_fiscal_year.py
> +        """
should `self.ensure_one()`.

2023-05-19 10:03 UTC, hieulucky111 commented on hr_payroll_period/models/hr_payslip.py
> +            if slip.hr_period_id:
`if slip.hr_period_id and slip.hr_period_id.company_id != slip.company_id:`

2023-05-19 10:03 UTC, hieulucky111 commented on hr_payroll_period/models/hr_payslip_run.py
> +            if run.hr_period_id:
`if run.hr_period_id and run.hr_period_id.company_id != run.company_id:`

2023-05-19 10:03 UTC, hieulucky111 commented on hr_payroll_period/models/hr_payslip_run.py
> +            if run.hr_period_id:
`if run.hr_period_id and run.hr_period_id.schedule_pay != run.schedule_pay:`

2023-05-19 10:03 UTC, hieulucky111 commented on hr_payroll_period/models/hr_fiscal_year.py
> +    @api.model
should remove this one as well?

2023-05-19 13:47 UTC, JuanyDForgeflow commented
@hieulucky111 please take a look at it again, it's fixed now

2023-05-22 08:30 UTC, MiquelRForgeFlow approved these changes
LGTM

2023-05-22 08:40 UTC, hieulucky111 approved these changes
LGTM

2023-05-23 23:36 UTC, nimarosa commented
/ocabot merge nobump

2023-05-23 23:36 UTC, nimarosa commented
/ocabot migration hr_payroll_period

2023-05-23 23:43 UTC, merged