[14.0][FIX] multicompanies
OCA/payroll pull request #121
Opened 2023-03-28 05:44 UTC by FernandoRomera

2023-03-28 05:48 UTC, FernandoRomera commented
Solved #116

2023-03-28 05:50 UTC, FernandoRomera commented
@nimarosa 
Can you review?

2023-03-28 06:35 UTC, mtelahun requested changes
Code review seems Ok, but it's hard to tell because you mixed code changes with refactoring. Mixing code changes with formatting changes makes it hard for reviewers to understand exactly what you changed. Even if you don't want to create separate PRs for them you should at least put them in separate commits (not in one big commit like this one).

2023-03-28 06:35 UTC, mtelahun commented on payroll_account/models/hr_contract.py
> +logger = logging.getLogger(__name__)
You don't need a logger if you are not using it.

2023-03-28 06:35 UTC, mtelahun commented on payroll_account/models/hr_payslip_line.py
> +logger = logging.getLogger(__name__)
Same here. No need for logging.

2023-03-28 06:35 UTC, mtelahun commented on payroll_account/models/hr_payslip_run.py
> +logger = logging.getLogger(__name__)
see above

2023-03-28 06:35 UTC, mtelahun commented on payroll_account/models/hr_salary_rule.py
> +logger = logging.getLogger(__name__)
See above

2023-03-28 08:17 UTC, FernandoRomera commented
> Code review seems Ok, but it's hard to tell because you mixed code changes with refactoring. Mixing code changes with formatting changes makes it hard for reviewers to understand exactly what you changed. Even if you don't want to create separate PRs for them you should at least put them in separate commits (not in one big commit like this one).

Ok, thanks for the explanation.

2023-03-28 08:26 UTC, FernandoRomera commented
Replace in models/hr_salary_rule.py
domain=[("deprecated", "=", False)]
by
domain=[("deprecated", "=", False), ("company_id", "=", company_id)],

2023-03-28 10:20 UTC, nimarosa commented
@FernandoRomera Like @mtelahun said, we need you to respect OCA guidelines for PRs. I edited the title of the PR, this should also be the commit message, because module names are used for migration scripts and bots. 

Also the refactoring and the changes should be in separated commit but we can pass on that for now. 

Please if you can, do a reword of the commit message to match PR title, and we can merge this.

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst

2023-03-28 11:26 UTC, FernandoRomera commented
@nimarosa 
Done, thanks.

2023-03-29 15:40 UTC, AntoniRomera approved these changes

2023-03-29 15:44 UTC, MRomeera approved these changes

2023-03-31 06:55 UTC, FernandoRomera commented
@nimarosa 
Can you review? and if is fine merge, thanks.

2023-03-31 10:14 UTC, nimarosa commented
/ocabot merge patch

2023-03-31 10:14 UTC, nimarosa approved these changes

2023-03-31 10:20 UTC, merged