[14.0][FIX] hr_payroll_period: remove warnings
OCA/payroll pull request #131
Opened 2023-10-23 08:14 UTC by renda-dev

Remove the following warnings from `hr_payroll_period` installation;

```
WARNING devel odoo.fields: Field hr.employee.base.contract_id with unknown comodel_name None 
WARNING devel odoo.fields: Field hr.employee.public.contract_id with unknown comodel_name None 
WARNING devel odoo.fields: Field hr.contract.schedule_pay: unknown parameter 'oldname', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it
```

2023-11-07 13:22 UTC, nimarosa commented
@renda-dev The changes are ok. Please do not change the version number, it will be changed automatically when i merge this PR. Please make the changes and we can merge this.

2023-11-07 13:22 UTC, nimarosa requested changes

2023-11-07 13:22 UTC, nimarosa commented on hr_payroll_period/__manifest__.py
> +    "version": "14.0.1.0.1",
Please do not change the version number here.

2024-01-04 11:02 UTC, aleuffre approved these changes
LGTM

2024-01-05 08:46 UTC, renda-dev commented
Friendly reminder :) @nimarosa

2024-01-05 10:56 UTC, nimarosa commented
@renda-dev Test are failing. Pre-commit and runboat. 
We can't merge until they are all green. Please check that out and rebase the PR into 14.0 branch to trigger the tests again.

2024-01-05 16:18 UTC, aleuffre commented
> @renda-dev The changes are ok. Please do not change the version number, it will be changed automatically when i merge this PR. Please make the changes and we can merge this.

As far as I knew, in case of a migration script, you have to change number version manually so it matches the number of the migration folder, no?

2024-01-05 16:34 UTC, aleuffre commented
Fixed pre-commit in https://github.com/OCA/payroll/pull/139

2024-01-08 08:15 UTC, renda-dev commented
Ready! Please, let me know what you think @nimarosa

2024-01-08 09:52 UTC, nimarosa commented
/ocabot merge minor

2024-01-08 09:55 UTC, merged