[17.0][MIG] hr_payroll_document: Migration to 17.0
OCA/payroll pull request #152
Opened 2024-05-20 14:10 UTC by peluko00

2024-05-27 11:23 UTC, lbarry-apsl commented
Hi @peluko00 ,

I have tried to test the module with the pdf document that comes in the tests but I get this notification "Employees not found".

It would be nice to add a usage section in the Readme.

2024-11-04 07:00 UTC, peluko00 commented
Hi @nimarosa, can you reopen the pr?

2024-11-04 09:22 UTC, peluko00 commented
Thanks!. Can you review it @nimarosa ?

2025-01-05 10:49 UTC, dreispt requested changes
Please remove the changes to the unrelated `payroll` module.
Changes introduced that are not strictly related to the migration are better in a separate commit. That helps understanding the changes and backporting them.

2025-01-07 07:28 UTC, peluko00 commented
> Please remove the changes to the unrelated `payroll` module. Changes introduced that are not strictly related to the migration are better in a separate commit. That helps understanding the changes and backporting them.

Done, thanks! Can you review it please @dreispt @nimarosa ?

2025-01-08 10:12 UTC, dreispt approved these changes
Technically it is OK for me.

But reading the description I have no idea what this does and what it is useful for.
A better and more instructional README would be nice.

2025-05-06 23:05 UTC, nimarosa commented
@peluko00 I agree with @dreispt , i have not idea why this module will be useful. But since it's not interact with payroll module, if you want it merged if you find it useful. please check runboat errors and we can merge it.

2025-05-09 05:46 UTC, peluko00 commented
> @peluko00 I agree with @dreispt , i have not idea why this module will be useful. But since it's not interact with payroll module, if you want it merged if you find it useful. please check runboat errors and we can merge it.

This module split payrolls of one document with multiple payrolls and insert this payrolls for each employee  by vat.
I'll do a new when I can for extend the README

2025-08-22 05:22 UTC, peluko00 commented
Can you review again please @nimarosa for merge please?

2025-10-19 13:26 UTC, Abranes approved these changes

2025-10-20 06:50 UTC, peluko00 commented
Seems it's ready to merge @nimarosa ?

2025-10-20 07:28 UTC, dreispt commented
/ocabot merge nobump
/ocabot migration hr_payroll_document

2025-10-20 07:33 UTC, merged