[13.0][OU-IMP] payroll: Add migration script since migration analysis.
OCA/payroll pull request #23
Opened 2021-12-09 12:28 UTC by victoralmau

Add migration script since migration analysis (https://github.com/OCA/payroll/pull/22).

Please @pedrobaeza can you review it?

@Tecnativa TT32606

2021-12-11 17:21 UTC, pedrobaeza requested changes
You have to make a copy of the `openupgrade_analysis.txt` file and call it `openupgrade_analysis_work.txt`, where you analyze by blocks the possible differences, or put `NOTHING TO DO` explaining the why's of each decision.

At least, I see 2 actions to do:

- There are `DEL` records with noupdate=1 that you should try to delete with the openupgradelib method (`delete_records_safely_by_xmlid` or similar)
- Some records that changes from noupdate=1 to noupdate=0 or vice versa, that you should also update its XML-ID with the corresponding method

but please check if anything more to do.

2021-12-20 16:38 UTC, victoralmau commented
Ok sorry, I have made the necessary changes after analyzing everything carefully.

2021-12-21 19:15 UTC, pedrobaeza commented on payroll/migrations/13.0.1.0.2/openupgrade_analysis_work.txt
> +# DONE: post-migration: Add to noupdate_changes
If they are new records, why do you need to add them to the noupdate changes?

2021-12-22 20:19 UTC, pedrobaeza approved these changes

2021-12-22 20:19 UTC, merged