[IMP][14.0] Improve salary rule form view
OCA/payroll pull request #66
Opened 2022-09-05 17:04 UTC by mtelahun

Not sure when it happened but the 'Condition' and 'Computation' sections have become unusable:

![Screenshot from 2022-09-05 15-16-41](https://user-images.githubusercontent.com/7964444/188492959-dd5d165a-6441-4473-a386-5df407ec62b9.png)

They now look like this:
![Screenshot from 2022-09-05 20-00-25](https://user-images.githubusercontent.com/7964444/188493003-2399874c-2d5d-4162-882d-e8f390bef5aa.png)

2022-09-05 17:09 UTC, nimarosa commented
Its weird, i just installed fresh and i see them correctly. Attach screenshot. 

<img width="1674" alt="Screen Shot 2022-09-05 at 14 09 33" src="https://user-images.githubusercontent.com/12401188/188493455-d6ec907f-11e3-4f02-af37-4814d35ca7b9.png">

2022-09-05 17:14 UTC, nimarosa commented
Also i don't see any change in your commits, only the order of the fields you are changing. Are you sure you don't have any external module messing up? I see you have some extra fields that indicates that you have private modules installed. 

Also you are removing the "<group>" tag so in your second screenshot the view it's not the same as always.

2022-09-05 17:20 UTC, mtelahun commented
Yeah, It's possible the problem is on my end. Although I could swear I haven't touched that part of the view...
Let me try it with a clean repository and I'll let you know.

2022-09-05 17:22 UTC, mtelahun commented
Regardless of the view changes though, the first commit [d9b5f2c](https://github.com/OCA/payroll/pull/66/commits/d9b5f2c73715aaccabb66b8cb5c302c4c500d6d6) is necessary

2022-09-05 17:23 UTC, nimarosa commented
Yes the first is okay. If you want to leave only that commit I merge this, if not, I can change this in the refactoring PR

2022-09-05 23:09 UTC, nimarosa commented
@mtelahun Did you find the problem? Please tell me if you want to leave first commit here and i merge or we close and i add that comment change in refactoring.

2022-09-06 04:46 UTC, mtelahun commented
I just ran it again with a clean build and only OCA/payroll installed. Same result
![image](https://user-images.githubusercontent.com/7964444/188548953-8ee8b3ff-cb63-4dea-b4c5-5564039efedc.png)

Can someone else please confirm if they see the same thing I  am? Thanks.

2022-09-06 05:01 UTC, mtelahun commented
I just tried a runboat build. Same result:
![image](https://user-images.githubusercontent.com/7964444/188550682-ae20faee-623a-445c-a5a5-e2dfa8cb1634.png)

@nimarosa I think the problem is on your end.

2022-09-06 05:29 UTC, nimarosa commented
@mtelahun Please try removing  colspan="4" from condition_python field and tell me if that solves it. I can test right now but looking at the code i think that's the problem.

If it is, please fix the commit and i can merge.

2022-09-06 05:32 UTC, mtelahun commented
With all due respect @nimarosa, I've already fixed it in the PR :grin:

On 06/09/2022 08:30, Nicolas Rodriguez Sande wrote:
>
> @mtelahun <https://github.com/mtelahun> Please try removing 
> colspan="4" from condition_python field and tell me if that solves it. 
> I can test right now but looking at the code i think that's the problem.
>
> If it is, please fix the commit and i can merge.
>
> —
> Reply to this email directly, view it on GitHub 
> <https://github.com/OCA/payroll/pull/66#issuecomment-1237675289>, or 
> unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AB4YOHGUPQH2OTRFO2XFLP3V43JGBANCNFSM6AAAAAAQFFEMDM>.
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>
>

2022-09-06 05:42 UTC, nimarosa commented
From the same runboat in chrome browser. 
<img width="1674" alt="Screen Shot 2022-09-06 at 02 39 25" src="https://user-images.githubusercontent.com/12401188/188555331-bda3cb3b-05bb-4429-9323-8baf3010e596.png">

I'm starting to think that it is a browser related issue. That's why i suggested removing colspan because amount_python_compute don't have it and that field didn't broke in your screenshot.  

Will test with firefox tomorrow, but i think it's a browser issue. Or maybe a plugin interfering but no quite sure.

2022-09-06 05:43 UTC, nimarosa commented
From the same runboat in chrome browser.
<img width="1641" alt="Screen Shot 2022-09-06 at 02 42 54" src="https://user-images.githubusercontent.com/12401188/188555735-0cd447c3-1111-484f-bfa5-5081b1128261.png">


I'm starting to think that it is a browser related issue. That's why i suggested removing colspan because amount_python_compute don't have it and that field didn't broke in your screenshot.

Will test with firefox tomorrow, but i think it's a browser issue. Or maybe a plugin interfering but no quite sure.

2022-09-06 05:53 UTC, nimarosa commented
@mtelahun Yeah, tested from firefox and could reproduce the error. It only happens on firefox.

Removing colspan="4" inside the separator `<separator string="Company Contribution" />`, only change needed fixes everything. No need to change the views inside a div like the commit does.

2022-09-06 06:02 UTC, mtelahun commented
Ok. So it's a browser isssue. Now we're getting somewhere. 
I just tried it after removing colspan. Still not fixed.

2022-09-06 06:04 UTC, nimarosa commented
It's the colspan in separator, not in condition_python like i said earlier. I started removed colspans to see which is the one that is doing this to the view. Removed from Edit Form in the UI in runboat, and worked. Did you removed separator's colspan? Not the field one.

2022-09-06 06:04 UTC, mtelahun commented
Ahh yes. That fixed it.

2022-09-06 06:16 UTC, mtelahun commented
Should be ready now

2022-09-06 06:20 UTC, nimarosa requested changes
- colspan in python field can remain since it not affects and makes more wider the code block in chrome. 
- Do you want to add the comments in salary_rule help attribute? You removed it with the force push. 

@mtelahun Tell me and we merge

2022-09-06 06:20 UTC, nimarosa commented on payroll/views/hr_salary_rule_views.xml
> -                                    colspan="4"
This is not necessary since it makes wider the code block.

2022-09-06 06:20 UTC, nimarosa commented on payroll/views/hr_salary_rule_views.xml
> -                                    colspan="4"
This is not necessary since it makes wider the code block.

2022-09-06 11:20 UTC, mtelahun commented
Should be done now.

2022-09-06 11:36 UTC, nimarosa approved these changes

2022-09-06 11:37 UTC, nimarosa commented
/ocabot merge patch nobump

2022-09-06 11:39 UTC, nimarosa commented
/ocabot merge patch

2022-09-06 12:52 UTC, nimarosa commented
@pedrobaeza Do you know if the bot is functioning okay? I think it is freezed.

2022-09-06 13:05 UTC, pedrobaeza commented
Repeat the command to retry.

2022-09-06 13:38 UTC, nimarosa commented
/ocabot merge patch

2022-09-06 13:43 UTC, merged